sudo: false
language: java
jdk:
  - oraclejdk8

script:
  - gradle build
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ecse429-fall2018 -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey=ecse429-tutorial-05-ModeratelyComfortableChair -Dsonar.projectName=ecse429-tutorial-05-ModeratelyComfortableChair

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

