/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 19:39:05 GMT 2018
 */

package com.github.cseppento.gradle.evosuite.testprojects.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.cseppento.gradle.evosuite.testprojects.simple.Example;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Example example0 = new Example();
      int int0 = example0.proc(2, 0, 0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Example example0 = new Example();
      int int0 = example0.proc(0, 0, 1549);
      assertEquals(1550, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Example example0 = new Example();
      int int0 = example0.proc(1391, 2030, (-2765));
      assertEquals((-2765), int0);
  }
}
