/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 19:08:50 GMT 2018
 */

package com.github.cseppento.gradle.evosuite.testprojects.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut;
import java.util.SortedSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleObjectSut_ESTest extends SimpleObjectSut_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(843L);
      simpleObjectSut0.guessDivisor(843L);
      simpleObjectSut0.check();
      assertEquals(843L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(843L);
      simpleObjectSut0.guessDivisor(843L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(843L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 843 is already added as a divisor of 843
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor((-1L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid divisor: -1
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-1068L));
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(25L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 25 is not a divisor of 1068
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-1068L));
      SortedSet<Long> sortedSet0 = simpleObjectSut0.getDivisors();
      assertTrue(sortedSet0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      String string0 = simpleObjectSut0.toString();
      assertEquals("SimpleObjectSut of 0 with divisors []", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      long long0 = simpleObjectSut0.getValue();
      assertEquals(0L, long0);
  }
}
