/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:29:57 GMT 2018
 */

package com.github.cseppento.gradle.evosuite.testprojects.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut;
import java.util.SortedSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SimpleObjectSut_ESTest extends SimpleObjectSut_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(2535L);
      simpleObjectSut0.check();
      assertEquals(2535L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(152L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 152 is not a divisor of 1
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1L);
      simpleObjectSut0.guessDivisor(1L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(1L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1 is already added as a divisor of 1
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-1856L));
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor((-1856L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid divisor: -1856
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(2535L);
      simpleObjectSut0.guessDivisor(2535L);
      simpleObjectSut0.check();
      assertEquals(2535L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(2535L);
      SortedSet<Long> sortedSet0 = simpleObjectSut0.getDivisors();
      assertEquals(0, sortedSet0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(1L);
      String string0 = simpleObjectSut0.toString();
      assertEquals("SimpleObjectSut of 1 with divisors []", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(2243L);
      long long0 = simpleObjectSut0.getValue();
      assertEquals(2243L, long0);
  }
}
